---
application_path: "/webapps/{{ application_name }}"
application_runtime_path: "{{ application_path }}/run"
application_log_dir: "{{ application_path }}/logs"
application_user: "{{ application_name }}"
application_group: "{{ application_name }}"

nginx_static_root: "{{ application_path }}/static"
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_ssl_crt: "/etc/nginx/ssl/server.crt"
nginx_ssl_key: "/etc/nginx/ssl/server.key"

fetcher_log_file: "{{ application_log_dir }}/fetcher.log"

unicorn_sock_path: "{{ application_runtime_path }}/unicorn.sock"
