- name: install dependencies
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=36000
  with_items:
    - vim
    - build-essential
    - git
    - language-pack-en

- include: install_ruby.yml
- include: install_gems.yml
