- name: install dependencies
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=36000
  with_items:
    - nginx
    - supervisor
    - python-pika
    - rabbitmq-server

- name: enable service nginx
  service: name=nginx state=started enabled=yes

- name: enable service rabbitmq
  service: name=rabbitmq-server state=started enabled=yes

- include: create_users_and_groups.yml
- include: create_directories.yml
- include: setup_nginx.yml
- include: setup_supervisor.yml
